name: (Sigmath) Pytest UI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Pytest-API-Testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.
        playwright install 
        
    - name: Test dummy test with pytest
      run: |
        pytest test_oneplusone.py

    - name: Test simple session
      run:
        pytest test_simple_session.py  

  

    # - name: Archive Pytest test report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: SuperTest-test-report
    #     path: report
          
    # - name: Upload Pytest report to GitHub
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Pytest-test-report
    #     path: report